# Generated by Django 5.2.4 on 2025-07-20 02:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='family_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='family_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='identification_docs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='medical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('deceased', 'Deceased'), ('safe', 'Safe')], default='missing', max_length=20),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
